<?php
// $Id: bot_join.module,v 1.2 2006/11/12 23:37:52 morbus Exp $

/**
 * @file
 * Allows IRC commands to control the bot's channel list.
 */

/**
 * Implementation of hook_help().
 */
function bot_join_help($section) {
  switch ($section) {
    case '':
      return '';
  }
}

/**
 * Implementation of hook_menu().
 */
function bot_join_menu($may_cache) {
  $items = array();

  if ($may_cache) {

  }

  return $items;
}
